"""Automatic asset priors derived from official item names and interaction videos.

These are category-level defaults, not manual per-frame labels.
"""

from __future__ import annotations

from typing import Any


CATALOG: dict[str, dict[str, Any]] = {
    "item_001": {
        "label": "储物柜",
        "kind": "cabinet_2door",
        "size": (0.80, 0.38, 1.18),
        "mass": 32.0,
        "static": True,
        "color": (0.93, 0.93, 0.94),
        "material": "painted_wood",
        "density": 650.0,
        "joints": [
            {"name": "door_left", "type": "revolute", "axis": "z", "limits_deg": (0.0, 95.0)},
            {"name": "door_right", "type": "revolute", "axis": "z", "limits_deg": (-95.0, 0.0)},
        ],
    },
    "item_002": {
        "label": "果汁箱+果汁",
        "kind": "juice_box",
        "size": (0.36, 0.24, 0.22),
        "mass": 3.2,
        "static": False,
        "color": (0.93, 0.55, 0.12),
        "material": "cardboard",
        "density": 690.0,
        "joints": [
            {"name": "flap_front", "type": "revolute", "axis": "x", "limits_deg": (0.0, 110.0)},
        ],
    },
    "item_003": {
        "label": "储物边柜",
        "kind": "sideboard",
        "size": (1.55, 0.40, 0.72),
        "mass": 48.0,
        "static": True,
        "color": (0.93, 0.93, 0.94),
        "accent": (0.78, 0.64, 0.42),
        "material": "painted_wood",
        "density": 700.0,
        "joints": [
            {"name": "door_left", "type": "revolute", "axis": "z", "limits_deg": (0.0, 95.0)},
            {"name": "door_right", "type": "revolute", "axis": "z", "limits_deg": (-95.0, 0.0)},
            {"name": "drawer", "type": "prismatic", "axis": "y", "limits_m": (-0.32, 0.0)},
            {"name": "drawer_2", "type": "prismatic", "axis": "y", "limits_m": (-0.32, 0.0)},
        ],
    },
    "item_004": {
        "label": "转椅",
        "kind": "office_chair",
        "size": (0.68, 0.68, 0.88),
        "mass": 8.0,
        "static": False,
        "color": (0.90, 0.90, 0.91),
        "accent": (0.20, 0.20, 0.22),
        "material": "plastic",
        "density": 980.0,
        "joints": [
            {"name": "swivel", "type": "revolute", "axis": "z", "limits_deg": (-180.0, 180.0)},
        ],
    },
    "item_005": {
        "label": "落地灯",
        "kind": "floor_lamp",
        "size": (0.36, 0.36, 1.55),
        "mass": 5.5,
        "static": True,
        "color": (0.92, 0.91, 0.88),
        "accent": (0.72, 0.55, 0.22),
        "material": "metal",
        "density": 2700.0,
        "joints": [
            {"name": "shade", "type": "revolute", "axis": "x", "limits_deg": (-25.0, 25.0)},
        ],
    },
    "item_006": {
        "label": "L形靠背沙发",
        "kind": "l_sofa",
        "size": (1.85, 0.88, 0.80),
        "mass": 48.0,
        "static": True,
        "color": (0.86, 0.82, 0.74),
        "material": "fabric",
        "density": 120.0,
        "joints": [],
    },
    "item_007": {
        "label": "单人椅",
        "kind": "lounge_chair",
        "size": (0.70, 0.72, 0.82),
        "mass": 11.0,
        "static": False,
        "color": (0.86, 0.82, 0.74),
        "material": "fabric",
        "density": 180.0,
        "joints": [],
    },
    "item_008": {
        "label": "脚凳",
        "kind": "ottoman",
        "size": (0.62, 0.46, 0.42),
        "mass": 4.2,
        "static": False,
        "color": (0.86, 0.82, 0.74),
        "material": "fabric",
        "density": 160.0,
        "joints": [],
    },
    "item_009": {
        "label": "边桌",
        "kind": "side_table",
        "size": (0.55, 0.40, 0.46),
        "mass": 8.0,
        "static": True,
        "color": (0.10, 0.10, 0.11),
        "material": "plastic",
        "density": 700.0,
        "joints": [],
    },
    "item_010": {
        "label": "水果刀",
        "kind": "knife",
        "size": (0.22, 0.028, 0.022),
        "mass": 0.10,
        "static": False,
        "color": (0.90, 0.86, 0.78),
        "accent": (0.88, 0.84, 0.76),
        "material": "plastic",
        "density": 1200.0,
        "joints": [],
    },
    "item_011": {
        "label": "床头桌",
        "kind": "nightstand",
        "size": (0.42, 0.36, 0.52),
        "mass": 12.0,
        "static": True,
        "color": (0.94, 0.94, 0.95),
        "material": "painted_wood",
        "density": 700.0,
        "joints": [
            {"name": "door", "type": "revolute", "axis": "z", "limits_deg": (0.0, 95.0), "hinge": "xmax"},
        ],
    },
    "item_012": {
        "label": "六斗抽屉柜",
        "kind": "dresser_6",
        "size": (0.90, 0.45, 1.05),
        "mass": 42.0,
        "static": True,
        "color": (0.94, 0.94, 0.95),
        "material": "painted_wood",
        "density": 700.0,
        "joints": [
            {"name": f"drawer_{index}", "type": "prismatic", "axis": "y", "limits_m": (-0.30, 0.0)}
            for index in range(1, 7)
        ],
    },
    "item_013": {
        "label": "面包机",
        "kind": "toaster",
        "size": (0.30, 0.19, 0.21),
        "mass": 2.4,
        "static": False,
        "color": (0.62, 0.78, 0.88),
        "material": "plastic",
        "density": 1050.0,
        "accent": (0.42, 0.24, 0.14),
        "joints": [
            {"name": "lever_left", "type": "prismatic", "axis": "z", "limits_m": (-0.05, 0.0)},
            {"name": "lever_right", "type": "prismatic", "axis": "z", "limits_m": (-0.05, 0.0)},
            {"name": "knob_left", "type": "revolute", "axis": "y", "limits_deg": (-150.0, 150.0)},
            {"name": "knob_right", "type": "revolute", "axis": "y", "limits_deg": (-150.0, 150.0)},
            *[
                {"name": f"button_{index}", "type": "prismatic", "axis": "y", "limits_m": (0.0, 0.004)}
                for index in range(1, 9)
            ],
        ],
    },
    "item_014": {
        "label": "微波炉",
        "kind": "microwave",
        "size": (0.48, 0.38, 0.30),
        "mass": 12.0,
        "static": False,
        "color": (0.92, 0.92, 0.93),
        "accent": (0.72, 0.52, 0.32),
        "material": "metal",
        "density": 2700.0,
        "joints": [
            {"name": "door", "type": "revolute", "axis": "z", "limits_deg": (0.0, 110.0)},
            {"name": "dial", "type": "revolute", "axis": "y", "limits_deg": (-150.0, 150.0)},
            *[
                {"name": f"button_{index}", "type": "prismatic", "axis": "y", "limits_m": (0.0, 0.004)}
                for index in range(1, 6)
            ],
        ],
    },
    "item_015": {
        "label": "电饭煲",
        "kind": "rice_cooker",
        "size": (0.28, 0.28, 0.26),
        "mass": 3.8,
        "static": False,
        "color": (0.94, 0.94, 0.95),
        "material": "plastic",
        "density": 1050.0,
        "joints": [
            {"name": "lid", "type": "revolute", "axis": "x", "limits_deg": (0.0, 95.0)},
            {"name": "button", "type": "prismatic", "axis": "y", "limits_m": (0.0, 0.006)},
        ],
    },
    "item_016": {
        "label": "空气炸锅",
        "kind": "air_fryer",
        "size": (0.28, 0.28, 0.34),
        "mass": 4.6,
        "static": False,
        "color": (0.93, 0.93, 0.94),
        "material": "plastic",
        "density": 1050.0,
        "joints": [
            {"name": "basket", "type": "prismatic", "axis": "y", "limits_m": (-0.22, 0.0)},
            {"name": "knob_time", "type": "revolute", "axis": "y", "limits_deg": (-150.0, 150.0)},
            {"name": "knob_temp", "type": "revolute", "axis": "y", "limits_deg": (-150.0, 150.0)},
        ],
    },
    "item_017": {
        "label": "电热水壶",
        "kind": "kettle",
        "size": (0.22, 0.16, 0.26),
        "mass": 1.1,
        "static": False,
        "color": (0.88, 0.90, 0.92),
        "material": "plastic",
        "density": 1050.0,
        "joints": [
            {"name": "lid", "type": "revolute", "axis": "x", "limits_deg": (0.0, 80.0)},
        ],
    },
    "item_018": {
        "label": "笔记本电脑（thinkpad）",
        "kind": "laptop",
        "size": (0.32, 0.22, 0.022),
        "mass": 1.6,
        "static": False,
        "color": (0.18, 0.18, 0.20),
        "accent": (0.82, 0.10, 0.12),
        "material": "plastic",
        "density": 1200.0,
        "joints": [
            {"name": "screen", "type": "revolute", "axis": "x", "limits_deg": (0.0, 125.0), "hinge": "ymin"},
        ],
    },
    "item_019": {
        "label": "鼠标",
        "kind": "mouse",
        "size": (0.11, 0.062, 0.038),
        "mass": 0.09,
        "static": False,
        "color": (0.78, 0.58, 0.62),
        "material": "plastic",
        "density": 1050.0,
        "joints": [
            {"name": "wheel", "type": "revolute", "axis": "x", "limits_deg": (-180.0, 180.0)},
        ],
    },
    "item_020": {
        "label": "显示器",
        "kind": "monitor",
        "size": (0.70, 0.22, 0.42),
        "mass": 5.2,
        "static": True,
        "color": (0.10, 0.10, 0.11),
        "accent": (0.78, 0.12, 0.12),
        "material": "plastic",
        "density": 1100.0,
        "joints": [
            {"name": "tilt", "type": "revolute", "axis": "x", "limits_deg": (-10.0, 22.0)},
        ],
    },
    "item_021": {
        "label": "抽纸",
        "kind": "tissue_box",
        "size": (0.18, 0.08, 0.26),
        "mass": 0.38,
        "static": False,
        "color": (0.62, 0.82, 0.92),
        "material": "plastic",
        "density": 400.0,
        "joints": [],
    },
    "item_022": {
        "label": "卷纸",
        "kind": "toilet_paper",
        "size": (0.36, 0.18, 0.26),
        "mass": 1.8,
        "static": False,
        "color": (0.45, 0.78, 0.32),
        "material": "plastic",
        "density": 250.0,
        "joints": [],
    },
    "item_023": {
        "label": "马克杯",
        "kind": "mug",
        "size": (0.09, 0.12, 0.10),
        "mass": 0.32,
        "static": False,
        "color": (0.22, 0.24, 0.18),
        "accent": (0.78, 0.70, 0.54),
        "material": "ceramic",
        "density": 2300.0,
        "joints": [],
    },
    "item_024": {
        "label": "垃圾桶",
        "kind": "trash_can",
        "size": (0.24, 0.24, 0.30),
        "mass": 0.8,
        "static": False,
        "color": (0.92, 0.78, 0.12),
        "material": "plastic",
        "density": 950.0,
        "joints": [],
    },
    "item_025": {
        "label": "薯片袋",
        "kind": "chip_bag",
        "size": (0.18, 0.08, 0.28),
        "mass": 0.18,
        "static": False,
        "color": (0.94, 0.52, 0.16),
        "material": "plastic",
        "density": 920.0,
        "joints": [],
    },
    "item_026": {
        "label": "罐装薯片",
        "kind": "chip_can",
        "size": (0.08, 0.08, 0.27),
        "mass": 0.22,
        "static": False,
        "color": (0.18, 0.72, 0.22),
        "accent": (0.95, 0.82, 0.12),
        "material": "cardboard",
        "density": 690.0,
        "joints": [
            {"name": "lid", "type": "revolute", "axis": "x", "limits_deg": (0.0, 110.0)},
        ],
    },
    "item_027": {
        "label": "酸菜鱼调味料",
        "kind": "seasoning_box",
        "size": (0.22, 0.10, 0.16),
        "mass": 0.28,
        "static": False,
        "color": (0.86, 0.22, 0.16),
        "material": "cardboard",
        "density": 500.0,
        "joints": [
            {"name": "flap", "type": "revolute", "axis": "x", "limits_deg": (0.0, 120.0)},
        ],
    },
    "item_028": {
        "label": "锅铲",
        "kind": "spatula",
        "size": (0.34, 0.09, 0.03),
        "mass": 0.14,
        "static": False,
        "color": (0.55, 0.42, 0.28),
        "material": "wood",
        "density": 700.0,
        "joints": [],
    },
    "item_029": {
        "label": "木碗",
        "kind": "bowl",
        "size": (0.16, 0.16, 0.07),
        "mass": 0.22,
        "static": False,
        "color": (0.42, 0.26, 0.14),
        "material": "wood",
        "density": 700.0,
        "joints": [],
    },
    "item_030": {
        "label": "木质兔子盘子",
        "kind": "plate",
        "size": (0.24, 0.20, 0.028),
        "mass": 0.28,
        "static": False,
        "color": (0.82, 0.68, 0.46),
        "material": "wood",
        "density": 700.0,
        "joints": [],
    },
    "item_031": {
        "label": "砧板",
        "kind": "cutting_board",
        "size": (0.38, 0.22, 0.018),
        "mass": 0.55,
        "static": False,
        "color": (0.68, 0.46, 0.26),
        "material": "wood",
        "density": 700.0,
        "joints": [],
    },
    "item_032": {
        "label": "炒锅",
        "kind": "wok",
        "size": (0.34, 0.34, 0.14),
        "mass": 1.6,
        "static": False,
        "color": (0.10, 0.10, 0.10),
        "accent": (0.55, 0.32, 0.18),
        "material": "metal",
        "density": 7800.0,
        "joints": [
            {"name": "lid", "type": "revolute", "axis": "x", "limits_deg": (0.0, 90.0)},
        ],
    },
    "item_033": {
        "label": "茶水间内部环境",
        "kind": "pantry_scene",
        "size": (4.2, 3.2, 2.6),
        "mass": 0.0,
        "static": True,
        "color": (0.92, 0.92, 0.93),
        "accent": (0.52, 0.53, 0.54),
        "material": "painted_wood",
        "density": 650.0,
        "joints": [
            {"name": "cabinet_door", "type": "revolute", "axis": "z", "limits_deg": (0.0, 95.0)},
            {"name": "drawer", "type": "prismatic", "axis": "y", "limits_m": (-0.28, 0.0)},
            {"name": "faucet", "type": "revolute", "axis": "z", "limits_deg": (-40.0, 40.0)},
            {"name": "glass_door", "type": "revolute", "axis": "z", "limits_deg": (0.0, 100.0), "hinge": "xmin"},
        ],
    },
    "item_034": {
        "label": "办公室环境",
        "kind": "office_scene",
        "size": (6.0, 4.5, 2.8),
        "mass": 0.0,
        "static": True,
        "color": (0.72, 0.55, 0.34),
        "accent": (0.91, 0.91, 0.92),
        "material": "wood",
        "density": 700.0,
        "joints": [
            {"name": "cabinet_door", "type": "revolute", "axis": "z", "limits_deg": (0.0, 95.0)},
            {"name": "desk_drawer", "type": "prismatic", "axis": "y", "limits_m": (-0.32, 0.0)},
            {"name": "blind", "type": "prismatic", "axis": "z", "limits_m": (-0.90, 0.0)},
            {"name": "door", "type": "revolute", "axis": "z", "limits_deg": (0.0, 110.0), "hinge": "ymin"},
        ],
    },
}


def all_item_ids() -> list[str]:
    return [f"item_{index:03d}" for index in range(1, 35)]
